name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # correspond au pattern v{{version}} sur pub.dev

jobs:
  publish:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Dry-run check
        run: flutter pub publish --dry-run

      - name: Publish to pub.dev via OIDC
        run: flutter pub publish --force
