name: Run Tests
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Clear Pub Cache
        run: rm -rf $HOME/.pub-cache

      - name: Modify pubspec.yaml
        run: |
          # Remplacer mockito version
          sed -i 's/mockito: \^5.4.5/mockito: 5.3.2/g' pubspec.yaml
          
          # Ajouter une section dependency_overrides pour forcer mockito 5.3.2
          cat >> pubspec.yaml << EOL
          
          dependency_overrides:
            mockito: 5.3.2
            analyzer: 5.13.0
          EOL
          
          # Vérifier le résultat
          cat pubspec.yaml

      - name: Install Dependencies
        run: flutter pub get

      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run Tests
        run: flutter test

