name: Run Tests
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Clear Pub Cache
        run: rm -rf $HOME/.pub-cache

      - name: Install Dependencies
        run: flutter clean

      - name: Force mockito version
        run: |
          sed -i 's/mockito: \^5.3.2/mockito: 5.3.2/g' pubspec.yaml
          cat pubspec.yaml | grep mockito

      - name: Install Dependencies
        run: flutter pub get

      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run Tests
        run: flutter test

